Web Scraping a web page to retrive the data . Here we have taken shine.com as our website to retrive the data.
We used beautiful Soup for scraping.

In [ ]:
#Importing required libraries.
import requests
from bs4 import BeautifulSoup

#Defining a function that downloads web page for given job role
def get_job_openings(role):
    #construct url
    job_search_url='https://www.shine.com/job-search/' + role

    #Get html page content using request
    response=requests.get(job_search_url)

    #Ensure that response is valid or not
    if response.status_code != 200:
        print('status code :',response.status_code)
        raise exception('failed to fetch web page'+ job_search_url)

    #Constructing a beautifulsoup doc
    doc=BeautifulSoup(response.text)
    return doc
doc=get_job_openings('any role')
#Defining a function to retrive the company name.
def get_company_names(doc):
    selection_class='jobCard_jobCard_cName__mYnow'
    company_name_tags=doc.find_all('div',{'class':selection_class})
    company_names=[]
    for company in company_name_tags:
        name_of_company = company.find('span')
        if name_of_company:
            company_names.append(company.text)
    return company_names
company_name=get_company_names(doc)

#Defining a function for the job title or we can say job heading.
def job_heading(doc):
    job_header_tags=doc.find_all('h2', itemprop="name")
    job_head=[]
    for header in job_header_tags:
        job_head.append(header.text.strip())
    return job_head
job_highlight=job_heading(doc)

#Creating a dictionary to format the data that we retrived.
dic={'company name':[],'job heading':[]}
dic['company name'].extend(get_company_names(doc))
dic['job heading'].extend(job_heading(doc))
dic
#Uploading the dictionary into dataframe using pandas.
import pandas as pd
df=pd.DataFrame.from_dict(dic)
#Creating a loop to get openings for different roles at a time.
def main_function(roles):
    dic={'job heading':[],'company name':[]}
    for i in roles:
        doc=get_job_openings(i)
        dic['job heading'].extend(job_heading(doc))
        dic['company name'].extend(get_company_names(doc))
    return dic
ab=main_function(['business-analyst','software-developer','Data Analyst','Associate-engineer','software-engineer'])
df = pd.DataFrame.from_dict(ab,orient='index')
df = df.transpose()
df

,job heading,company name
0,Apply for Business Analyst/Senior Business Ana...,Meesho
1,Business Analyst,Orcapod Consulting Services Pvt. Lt...
2,Business Analyst-techno-functional-Oil/Gas/Pet...,Orcapod Consulting Services Pvt. Lt...
3,Business Analyst-Digital Transformation-Banking,Orcapod Consulting Services Pvt. Lt...
4,Business Analyst,Orcapod Consulting Services Pvt. Lt...
...,...,...
95,Software Developer,Royal Enterprises.
96,Senior Software Engineer (Backend),GFL RECRUITMENT PRIVATE LIMITED
97,Software Engineer/Sr.Software Engineer (Micros...,Nous Info Systems
98,Sr. Software Developer - Bangalore,MNR Solutions Pvt Ltd
99,"fresher Software Developer,php,web developer,...",Guidance Placement Hiring For java ...